config/routes.rb
SlimScale::Application.routes.draw do
  get "users/show"

  get "authentications/create"

  get "authentications/index"

  get "authentications/destroy"

  resources :authentications
  
  match 'post-weight' => 'weights#create'
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'sessions#failure'
  match 'sign_out' => 'sessions#destroy'
  match 'lookup' => "weights#lookup"
  
  get "pages/home"

  resources :users

  match 'results' => "users#index"
  

  root :to => "pages#home"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :provider, :uid
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :weight
  
  has_many :authentications
  has_one :qrcode, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth["provider"],omniauth["uid"])
    if authentication
      redirect_to users_show_path
    else
      user = User.new
      user.authentications.build(:provider => omniauth["provider"], :uid => omniauth["uid"])

      user.name = omniauth["info"]["name"]
      user.email = omniauth["info"]["email"]
      user.save!
      redirect_to users_show_path
    end
    session[:name] = omniauth["info"]["name"]
    session[:uid] = omniauth["uid"]
    session[:provider] = omniauth["provider"]
    session[:avatar] = omniauth["info"]["image"]
  end

  def index
  end

  def destroy
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    authentication = Authentication.find_by_uid(session[:uid])
    user = User.find_by_id(authentication[:user_id])
    @notes = user.notes
  end

  def new
    @note = Note.new
  end

  def create
    authentication = Authentication.find_by_uid(session[:uid])
    user = User.find_by_id(authentication[:user_id])
    @note = Note.new(params[:note])
    @note.user_id = user.id
    if @note.save
      redirect_to notes_url, :notice => "Successfully created note."
    else
      render :action => 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update_attributes(params[:note])
      redirect_to notes_url, :notice  => "Successfully updated note."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_url, :notice => "Successfully destroyed note."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/qrcode_controller.rb
class QrcodeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #raise request.env['omniauth.auth'].to_yaml
    # flash[:notice] = "Successfully logged in"
    # session[:name] = request.env['omniauth.auth']['user_info']['name']
    # session[:uid] = request.env['omniauth.auth']['uid']
    # session[:provider] = request.env['omniauth.auth']['provider']
    # session[:avatar] = request.env['omniauth.auth']['user_info']['image']
    # session[:nickname] = request.env['omniauth.auth']['user_info']['nickname']
    # redirect_to root_path
  end

  def failure
    flash[:alert] = "Authentication failure"
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to pages_home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    authentication = Authentication.find_by_uid(session[:uid])
    @user = User.find_by_id(authentication[:user_id])
    flash[:notice] = "Signed in successfully"

    if @user
      @qr = RQRCode::QRCode.new(@user.email, :size => 3, :level => :h )
    end
    
    # respond_to do |format|
    #   format.html {  }
    #   format.svg { render :qrcode => @user.email, :level => :l, :unit => 10 }
    #   format.png { render :qrcode => @user.email }
    # end
  end

  def index
    @users = User.all
  end

end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  
  def create
    user = User.find_by_email(params["email"])
    if user
      user.update_attributes({:weight => params["weight"]})
    end
    render :nothing => true
  end

  def lookup
    user = User.find_by_email(params["email"])
    if user.weight != nil
      render :json => {:weight => user.weight}
    else
      render :json => {:weight => nil}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weight_helper.rb
module WeightHelper
end

app/views/authentications/create.html.haml
%h1 Authentications#create
%p Find me in app/views/authentications/create.html.haml

app/views/authentications/destroy.html.haml
%h1 Authentications#destroy
%p Find me in app/views/authentications/destroy.html.haml

app/views/authentications/index.html.haml
%h1 Authentications#index
%p Find me in app/views/authentications/index.html.haml

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    = csrf_meta_tag

    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
	
    = stylesheet_link_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css"

    = stylesheet_link_tag "application"  
    = javascript_include_tag "application"
    = javascript_include_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"

    = yield(:head)

  %body
    #container
        
      .flash
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

    %div{"data-role" => "page"}
      %div{"data-role" => "header"}
        %h1= yield :heading
	  
      %div{"data-role" => "content"}
        = yield

app/views/pages/home.html.haml
- content_for :heading do
  .login
    %h2.logo SLIMSCALE
    - if session[:uid].present?
      %div
        = session[:name]
      %div
        = image_tag session[:avatar]
      %div
        = session[:provider]
      %div
        //not sure if we need this image, causing a broken image
        //%img{:src => "/images/authbuttons/png/#{session[:provider]}_32.png"}
      %div
        = link_to "Sign out", sign_out_path, :rel => "external"
    - else
      %div
%div.container
  %div.body
    %div.login
      = link_to image_tag(asset_path("fblarge.png")), "/auth/facebook", :rel => "external"

  

app/views/users/index.html.haml
- content_for :heading do
  .login
    %h2.logo SLIMSCALE
    - if session[:uid].present?
      %div
        = session[:name]
      %div
        = image_tag session[:avatar]
      %div
        = session[:provider]
      %div
        //not sure if we need this image, causing a broken image
        //%img{:src => "/images/authbuttons/png/#{session[:provider]}_32.png"}
      %div
        = link_to "Sign out", sign_out_path, :rel => "external"
    - else
      %div
%div.container
  %div.body.results
    %table
      %th
      %th name
      %th weight
      - @users.each do |user|
        %tr
          %td
            %img{:src => "https://graph.facebook.com/#{user.authentications.first.uid}/picture?type=large"}
          %td= user.name
          - if user.weight != nil
            %td= user.weight
          - else
            %td N/A

app/views/users/show.html.haml
- content_for :heading do
  = "Hi #{@user.name}!"

:css
  table#qr-code {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  td {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
    padding: 0;
    margin: 0;
    width: 10px;
    height: 10px;
  }
  td.black { background-color: #000; }
  td.white { background-color: #fff; }

%table#qr-code
  - @qr.modules.each_index do |x|
    %tr
      - @qr.modules.each_index do |y|
        - if @qr.dark?(x,y)
          %td.black/
        - else
          %td.white/

#loader

#digital-scale.value

%button#track-weight{"data-role"=>"button","data-theme"=>"a","data-facebook-id"=>"#{@user.email}"}
  Track Weight
%br
= link_to "All User Results", users_path, "data-role" => "button"